export {
  allocateOpaqueId,
  assertClientId,
  assertEntityId,
  assertOpaqueSceneId,
  assertOpaqueTourId,
  createOpaqueId,
  isOpaqueHotspotId,
  isOpaqueSceneId,
  isOpaqueTourId,
  OPAQUE_HOTSPOT_ID_PREFIX,
  OPAQUE_NAMING_ID_PREFIX,
  OPAQUE_SCENE_ID_PREFIX,
  OPAQUE_TOUR_ID_PREFIX,
} from '../../src/utils/opaqueId.mjs';
